services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: zpi


  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - mongo
    ports:
      - "8000:8000"
